//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipamentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computadores
    {
        public int IDComputador { get; set; }
        public string NrPratrimonio { get; set; }
        public int IDDepartamento { get; set; }
        public int IDTipo { get; set; }
        public int IDMarca { get; set; }
        public int IDProcessador { get; set; }
        public string Memoria { get; set; }
        public string Disco { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Processador Processador { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
