//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipamentos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PerifericosEntities : DbContext
    {
        public PerifericosEntities()
            : base("name=PerifericosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computadores> Computadores { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Monitor> Monitor { get; set; }
        public virtual DbSet<Processador> Processador { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
    }
}
