//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipamentos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        public int IDMonitor { get; set; }
        public string NrPatrimonio { get; set; }
        public int IDDepartamento { get; set; }
        public string Tamanho { get; set; }
        public int IDMarca { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
