//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int IdFuncionario { get; set; }
        public string Nome { get; set; }
        public decimal Salario { get; set; }
        public int IdSetor { get; set; }
        public string Endereco { get; set; }
    
        public virtual Setor Setor { get; set; }
    }
}
