//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace iPlace
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Produto
    {
        public int IdProduto { get; set; }
        [MinLength(2)]
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Cor { get; set; }
        public decimal Valor { get; set; }
    }
}
