//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimento
    {
        public int IDMovimento { get; set; }
        public int IDCategoria { get; set; }
        public int IDUsuario { get; set; }
        public int NrPeriodo { get; set; }
        public System.DateTime DtLancamento { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
